// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'abd6ea91d9db085081451075f74b7ccc4f39b6a7fa201cf7611a90a2cb9cdf74'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Department: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly max_level: CodecTypes['pg/int4@1']['output'];
    };
    readonly Document: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly documentType: CodecTypes['pg/text@1']['output'];
      readonly fileName: CodecTypes['pg/text@1']['output'];
      readonly filePath: CodecTypes['pg/text@1']['output'];
      readonly status: 'pending' | 'approved' | 'rejected';
      readonly uploadDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly reviewDate: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly lockedBy: CodecTypes['pg/int4@1']['output'] | null;
      readonly lockedAt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly studentId: CodecTypes['pg/int4@1']['output'];
      readonly staffId: CodecTypes['pg/int4@1']['output'];
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Notification: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/date-temporal@1']['output'];
      readonly isRead: CodecTypes['pg/bool@1']['output'];
      readonly studentId: CodecTypes['pg/int4@1']['output'];
      readonly staffId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Registration: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly status: 'not started' | 'ongoing' | 'completed' | 'failed';
      readonly dateRegistered: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly studentId: CodecTypes['pg/int4@1']['output'];
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
    };
    readonly requiredDocuments: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
    };
    readonly requiredDocumentsMAPstudentCategories: {
      readonly stuCategoryId: CodecTypes['pg/int4@1']['output'];
      readonly reqDocsId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Session: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly startDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly endDate: CodecTypes['pg/date-temporal@1']['output'] | null;
    };
    readonly Staff: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly staffId: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly matric_no: CodecTypes['pg/text@1']['output'];
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly level: CodecTypes['pg/int4@1']['output'];
      readonly mode_of_entry: 'utme' | 'transfer' | 'direct entry';
      readonly graduated: CodecTypes['pg/bool@1']['output'];
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly academicSession: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
    };
    readonly studentCategories: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly category: 'fresher' | 'returning' | 'finalist';
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/date-temporal@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly mustResetPassword: CodecTypes['pg/bool@1']['output'];
      readonly passwordRestAt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly role: 'student' | 'staff' | 'admin';
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Department: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly max_level: CodecTypes['pg/int4@1']['input'];
    };
    readonly Document: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly documentType: CodecTypes['pg/text@1']['input'];
      readonly fileName: CodecTypes['pg/text@1']['input'];
      readonly filePath: CodecTypes['pg/text@1']['input'];
      readonly status: 'pending' | 'approved' | 'rejected';
      readonly uploadDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly reviewDate: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly lockedBy: CodecTypes['pg/int4@1']['input'] | null;
      readonly lockedAt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly studentId: CodecTypes['pg/int4@1']['input'];
      readonly staffId: CodecTypes['pg/int4@1']['input'];
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Notification: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/date-temporal@1']['input'];
      readonly isRead: CodecTypes['pg/bool@1']['input'];
      readonly studentId: CodecTypes['pg/int4@1']['input'];
      readonly staffId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Registration: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly status: 'not started' | 'ongoing' | 'completed' | 'failed';
      readonly dateRegistered: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly studentId: CodecTypes['pg/int4@1']['input'];
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
    };
    readonly requiredDocuments: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
    };
    readonly requiredDocumentsMAPstudentCategories: {
      readonly stuCategoryId: CodecTypes['pg/int4@1']['input'];
      readonly reqDocsId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Session: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly startDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly endDate: CodecTypes['pg/date-temporal@1']['input'] | null;
    };
    readonly Staff: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly staffId: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly matric_no: CodecTypes['pg/text@1']['input'];
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly level: CodecTypes['pg/int4@1']['input'];
      readonly mode_of_entry: 'utme' | 'transfer' | 'direct entry';
      readonly graduated: CodecTypes['pg/bool@1']['input'];
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly academicSession: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
    };
    readonly studentCategories: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly category: 'fresher' | 'returning' | 'finalist';
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/date-temporal@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly mustResetPassword: CodecTypes['pg/bool@1']['input'];
      readonly passwordRestAt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly role: 'student' | 'staff' | 'admin';
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly department: {
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly max_level: CodecTypes['pg/int4@1']['output'];
    };
    readonly document: {
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly documentType: CodecTypes['pg/text@1']['output'];
      readonly fileName: CodecTypes['pg/text@1']['output'];
      readonly filePath: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly lockedAt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly lockedBy: CodecTypes['pg/int4@1']['output'] | null;
      readonly reviewDate: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
      readonly staffId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'pending' | 'approved' | 'rejected';
      readonly studentId: CodecTypes['pg/int4@1']['output'];
      readonly uploadDate: CodecTypes['pg/date-temporal@1']['output'];
    };
    readonly notification: {
      readonly createdAt: CodecTypes['pg/date-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isRead: CodecTypes['pg/bool@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly staffId: CodecTypes['pg/int4@1']['output'];
      readonly studentId: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly registration: {
      readonly dateRegistered: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'not started' | 'ongoing' | 'completed' | 'failed';
      readonly studentId: CodecTypes['pg/int4@1']['output'];
    };
    readonly requiredDocuments: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly requiredDocumentsMAPstudentCategories: {
      readonly reqDocsId: CodecTypes['pg/int4@1']['output'];
      readonly stuCategoryId: CodecTypes['pg/int4@1']['output'];
    };
    readonly session: {
      readonly endDate: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly startDate: CodecTypes['pg/date-temporal@1']['output'];
    };
    readonly staff: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly staffId: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly student: {
      readonly academicSession: CodecTypes['pg/text@1']['output'] | null;
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
      readonly graduated: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly level: CodecTypes['pg/int4@1']['output'];
      readonly matric_no: CodecTypes['pg/text@1']['output'];
      readonly mode_of_entry: 'utme' | 'transfer' | 'direct entry';
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly studentCategories: {
      readonly category: 'fresher' | 'returning' | 'finalist';
      readonly id: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/date-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly mustResetPassword: CodecTypes['pg/bool@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly passwordRestAt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly role: 'student' | 'staff' | 'admin';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly department: {
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly max_level: CodecTypes['pg/int4@1']['input'];
    };
    readonly document: {
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly documentType: CodecTypes['pg/text@1']['input'];
      readonly fileName: CodecTypes['pg/text@1']['input'];
      readonly filePath: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly lockedAt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly lockedBy: CodecTypes['pg/int4@1']['input'] | null;
      readonly reviewDate: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
      readonly staffId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'pending' | 'approved' | 'rejected';
      readonly studentId: CodecTypes['pg/int4@1']['input'];
      readonly uploadDate: CodecTypes['pg/date-temporal@1']['input'];
    };
    readonly notification: {
      readonly createdAt: CodecTypes['pg/date-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isRead: CodecTypes['pg/bool@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly staffId: CodecTypes['pg/int4@1']['input'];
      readonly studentId: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly registration: {
      readonly dateRegistered: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'not started' | 'ongoing' | 'completed' | 'failed';
      readonly studentId: CodecTypes['pg/int4@1']['input'];
    };
    readonly requiredDocuments: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly requiredDocumentsMAPstudentCategories: {
      readonly reqDocsId: CodecTypes['pg/int4@1']['input'];
      readonly stuCategoryId: CodecTypes['pg/int4@1']['input'];
    };
    readonly session: {
      readonly endDate: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly startDate: CodecTypes['pg/date-temporal@1']['input'];
    };
    readonly staff: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly staffId: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly student: {
      readonly academicSession: CodecTypes['pg/text@1']['input'] | null;
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly department:
        'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
      readonly graduated: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly level: CodecTypes['pg/int4@1']['input'];
      readonly matric_no: CodecTypes['pg/text@1']['input'];
      readonly mode_of_entry: 'utme' | 'transfer' | 'direct entry';
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly studentCategories: {
      readonly category: 'fresher' | 'returning' | 'finalist';
      readonly id: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/date-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly mustResetPassword: CodecTypes['pg/bool@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly passwordRestAt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly role: 'student' | 'staff' | 'admin';
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/int4@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    firstName: CodecTypes['pg/text@1']['output'];
    lastName: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/date-temporal@1']['output'];
    isActive: CodecTypes['pg/bool@1']['output'];
    mustResetPassword: CodecTypes['pg/bool@1']['output'];
    passwordRestAt: CodecTypes['pg/date-temporal@1']['output'] | null;
    role: 'student' | 'staff' | 'admin';
    readonly [RelationKeys]?: never;
  };
  export type public_Student = {
    id: CodecTypes['pg/int4@1']['output'];
    matric_no: CodecTypes['pg/text@1']['output'];
    department: 'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
    level: CodecTypes['pg/int4@1']['output'];
    mode_of_entry: 'utme' | 'transfer' | 'direct entry';
    graduated: CodecTypes['pg/bool@1']['output'];
    categoryId: CodecTypes['pg/int4@1']['output'] | null;
    academicSession: CodecTypes['pg/text@1']['output'] | null;
    userId: CodecTypes['pg/int4@1']['output'];
    departmentId: CodecTypes['pg/int4@1']['output'];
    dept: public_Department;
    documents: public_Document[];
    notifications: public_Notification[];
    registrations: public_Registration[];
    user: public_User;
    readonly [RelationKeys]?: 'dept' | 'documents' | 'notifications' | 'registrations' | 'user';
  };
  export type public_Staff = {
    id: CodecTypes['pg/int4@1']['output'];
    staffId: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    documents: public_Document[];
    notifications: public_Notification[];
    user: public_User;
    readonly [RelationKeys]?: 'documents' | 'notifications' | 'user';
  };
  export type public_Department = {
    id: CodecTypes['pg/int4@1']['output'];
    department: 'computer science' | 'software engineering' | 'data science' | 'cybersecurity';
    max_level: CodecTypes['pg/int4@1']['output'];
    students: public_Student[];
    readonly [RelationKeys]?: 'students';
  };
  export type public_Document = {
    id: CodecTypes['pg/int4@1']['output'];
    documentType: CodecTypes['pg/text@1']['output'];
    fileName: CodecTypes['pg/text@1']['output'];
    filePath: CodecTypes['pg/text@1']['output'];
    status: 'pending' | 'approved' | 'rejected';
    uploadDate: CodecTypes['pg/date-temporal@1']['output'];
    reviewDate: CodecTypes['pg/date-temporal@1']['output'] | null;
    comment: CodecTypes['pg/text@1']['output'] | null;
    lockedBy: CodecTypes['pg/int4@1']['output'] | null;
    lockedAt: CodecTypes['pg/date-temporal@1']['output'] | null;
    studentId: CodecTypes['pg/int4@1']['output'];
    staffId: CodecTypes['pg/int4@1']['output'];
    sessionId: CodecTypes['pg/int4@1']['output'];
    session: public_Session;
    staff: public_Staff;
    student: public_Student;
    readonly [RelationKeys]?: 'session' | 'staff' | 'student';
  };
  export type public_Session = {
    id: CodecTypes['pg/int4@1']['output'];
    sessionId: CodecTypes['pg/text@1']['output'];
    isActive: CodecTypes['pg/bool@1']['output'];
    startDate: CodecTypes['pg/date-temporal@1']['output'];
    endDate: CodecTypes['pg/date-temporal@1']['output'] | null;
    documents: public_Document[];
    registrations: public_Registration[];
    readonly [RelationKeys]?: 'documents' | 'registrations';
  };
  export type public_Registration = {
    id: CodecTypes['pg/int4@1']['output'];
    status: 'not started' | 'ongoing' | 'completed' | 'failed';
    dateRegistered: CodecTypes['pg/date-temporal@1']['output'] | null;
    studentId: CodecTypes['pg/int4@1']['output'];
    sessionId: CodecTypes['pg/int4@1']['output'];
    session: public_Session;
    student: public_Student;
    readonly [RelationKeys]?: 'session' | 'student';
  };
  export type public_studentCategories = {
    id: CodecTypes['pg/int4@1']['output'];
    category: 'fresher' | 'returning' | 'finalist';
    reqDocs: public_requiredDocuments[];
    readonly [RelationKeys]?: 'reqDocs';
  };
  export type public_requiredDocuments = {
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    isActive: CodecTypes['pg/bool@1']['output'];
    stuCategory: public_studentCategories[];
    readonly [RelationKeys]?: 'stuCategory';
  };
  export type public_requiredDocumentsMAPstudentCategories = {
    stuCategoryId: CodecTypes['pg/int4@1']['output'];
    reqDocsId: CodecTypes['pg/int4@1']['output'];
    category: public_studentCategories;
    docs: public_requiredDocuments;
    readonly [RelationKeys]?: 'category' | 'docs';
  };
  export type public_Notification = {
    id: CodecTypes['pg/int4@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    message: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/date-temporal@1']['output'];
    isRead: CodecTypes['pg/bool@1']['output'];
    studentId: CodecTypes['pg/int4@1']['output'];
    staffId: CodecTypes['pg/int4@1']['output'];
    staff: public_Staff;
    student: public_Student;
    readonly [RelationKeys]?: 'staff' | 'student';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Student: Models.public_Student;
    Staff: Models.public_Staff;
    Department: Models.public_Department;
    Document: Models.public_Document;
    Session: Models.public_Session;
    Registration: Models.public_Registration;
    studentCategories: Models.public_studentCategories;
    requiredDocuments: Models.public_requiredDocuments;
    requiredDocumentsMAPstudentCategories: Models.public_requiredDocumentsMAPstudentCategories;
    Notification: Models.public_Notification;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly department: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly department: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly max_level: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly document: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly documentType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fileName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly filePath: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pending'>;
                  };
                };
                readonly uploadDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly reviewDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly comment: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lockedBy: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly lockedAt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly studentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly staffId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly sessionId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'document_studentId_idx_bf255322';
                  readonly prefix: 'document_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'document_staffId_idx_ce92c64e';
                  readonly prefix: 'document_staffId_idx';
                  readonly columns: readonly ['staffId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'document_sessionId_idx_29f415d4';
                  readonly prefix: 'document_sessionId_idx';
                  readonly columns: readonly ['sessionId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'document';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'document';
                    readonly columns: readonly ['staffId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'document';
                    readonly columns: readonly ['sessionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'session';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly notification: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly isRead: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly staffId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'notification_studentId_idx_bf255322';
                  readonly prefix: 'notification_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'notification_staffId_idx_ce92c64e';
                  readonly prefix: 'notification_staffId_idx';
                  readonly columns: readonly ['staffId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'notification';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'notification';
                    readonly columns: readonly ['staffId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly registration: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'not started'>;
                  };
                };
                readonly dateRegistered: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly studentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly sessionId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['studentId'] },
                { readonly columns: readonly ['sessionId'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'registration';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'registration';
                    readonly columns: readonly ['sessionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'session';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly requiredDocuments: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly requiredDocumentsMAPstudentCategories: {
              columns: {
                readonly stuCategoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reqDocsId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['stuCategoryId', 'reqDocsId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'requiredDocumentsMAPstudentCategories_stuCategoryId_id_bedf0fd7';
                  readonly prefix: 'requiredDocumentsMAPstudentCategories_stuCategoryId_id';
                  readonly columns: readonly ['stuCategoryId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'requiredDocumentsMAPstudentCategories_reqDocsId_idx_3fd624fe';
                  readonly prefix: 'requiredDocumentsMAPstudentCategories_reqDocsId_idx';
                  readonly columns: readonly ['reqDocsId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'requiredDocumentsMAPstudentCategories';
                    readonly columns: readonly ['stuCategoryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'studentCategories';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'requiredDocumentsMAPstudentCategories';
                    readonly columns: readonly ['reqDocsId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'requiredDocuments';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly session: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly sessionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly startDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly endDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['sessionId'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly staff: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly staffId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly student: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly matric_no: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly department: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly level: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly mode_of_entry: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'utme'>;
                  };
                };
                readonly graduated: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly categoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly academicSession: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly departmentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['matric_no'] },
                { readonly columns: readonly ['userId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'student_departmentId_idx_8e261ed8';
                  readonly prefix: 'student_departmentId_idx';
                  readonly columns: readonly ['departmentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'student';
                    readonly columns: readonly ['departmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'department';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly studentCategories: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly mustResetPassword: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly passwordRestAt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'admin'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly dept: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'computer science',
                'software engineering',
                'data science',
                'cybersecurity',
              ];
            };
            readonly modeOfEntry: {
              readonly kind: 'valueSet';
              readonly values: readonly ['utme', 'transfer', 'direct entry'];
            };
            readonly registrationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['not started', 'ongoing', 'completed', 'failed'];
            };
            readonly stuCategory: {
              readonly kind: 'valueSet';
              readonly values: readonly ['fresher', 'returning', 'finalist'];
            };
            readonly uploadStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['pending', 'approved', 'rejected'];
            };
            readonly userRole: {
              readonly kind: 'valueSet';
              readonly values: readonly ['student', 'staff', 'admin'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly student: { readonly namespace: 'public' & NamespaceId; readonly model: 'Student' };
    readonly staff: { readonly namespace: 'public' & NamespaceId; readonly model: 'Staff' };
    readonly department: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Department';
    };
    readonly document: { readonly namespace: 'public' & NamespaceId; readonly model: 'Document' };
    readonly session: { readonly namespace: 'public' & NamespaceId; readonly model: 'Session' };
    readonly registration: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Registration';
    };
    readonly studentCategories: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'studentCategories';
    };
    readonly requiredDocuments: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'requiredDocuments';
    };
    readonly requiredDocumentsMAPstudentCategories: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'requiredDocumentsMAPstudentCategories';
    };
    readonly notification: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Notification';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Department: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly department: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly max_level: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly students: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departmentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'department';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly department: { readonly column: 'department' };
                readonly max_level: { readonly column: 'max_level' };
              };
            };
          };
          readonly Document: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly documentType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fileName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly filePath: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly uploadDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly reviewDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly comment: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lockedBy: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lockedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly staffId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Session';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly staff: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['staffId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'document';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly documentType: { readonly column: 'documentType' };
                readonly fileName: { readonly column: 'fileName' };
                readonly filePath: { readonly column: 'filePath' };
                readonly status: { readonly column: 'status' };
                readonly uploadDate: { readonly column: 'uploadDate' };
                readonly reviewDate: { readonly column: 'reviewDate' };
                readonly comment: { readonly column: 'comment' };
                readonly lockedBy: { readonly column: 'lockedBy' };
                readonly lockedAt: { readonly column: 'lockedAt' };
                readonly studentId: { readonly column: 'studentId' };
                readonly staffId: { readonly column: 'staffId' };
                readonly sessionId: { readonly column: 'sessionId' };
              };
            };
          };
          readonly Notification: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly message: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly isRead: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly staffId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly staff: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['staffId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'notification';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly message: { readonly column: 'message' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly isRead: { readonly column: 'isRead' };
                readonly studentId: { readonly column: 'studentId' };
                readonly staffId: { readonly column: 'staffId' };
              };
            };
          };
          readonly Registration: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dateRegistered: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Session';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'registration';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly status: { readonly column: 'status' };
                readonly dateRegistered: { readonly column: 'dateRegistered' };
                readonly studentId: { readonly column: 'studentId' };
                readonly sessionId: { readonly column: 'sessionId' };
              };
            };
          };
          readonly requiredDocuments: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly stuCategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'studentCategories';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reqDocsId'];
                };
                readonly through: {
                  readonly table: 'requiredDocumentsMAPstudentCategories';
                  readonly namespaceId: 'public';
                  readonly parentColumns: readonly ['reqDocsId'];
                  readonly childColumns: readonly ['stuCategoryId'];
                  readonly targetColumns: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'requiredDocuments';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly isActive: { readonly column: 'isActive' };
              };
            };
          };
          readonly requiredDocumentsMAPstudentCategories: {
            readonly fields: {
              readonly stuCategoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reqDocsId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'studentCategories';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['stuCategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly docs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'requiredDocuments';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['reqDocsId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'requiredDocumentsMAPstudentCategories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly stuCategoryId: { readonly column: 'stuCategoryId' };
                readonly reqDocsId: { readonly column: 'reqDocsId' };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly startDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly endDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
            };
            readonly relations: {
              readonly documents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['sessionId'];
                };
              };
              readonly registrations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Registration';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['sessionId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'session';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly sessionId: { readonly column: 'sessionId' };
                readonly isActive: { readonly column: 'isActive' };
                readonly startDate: { readonly column: 'startDate' };
                readonly endDate: { readonly column: 'endDate' };
              };
            };
          };
          readonly Staff: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly staffId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly documents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['staffId'];
                };
              };
              readonly notifications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Notification';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['staffId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'staff';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly staffId: { readonly column: 'staffId' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly Student: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly matric_no: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly department: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly level: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly mode_of_entry: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly graduated: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly categoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly academicSession: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly departmentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly dept: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['departmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly documents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly notifications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Notification';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly registrations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Registration';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'student';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly matric_no: { readonly column: 'matric_no' };
                readonly department: { readonly column: 'department' };
                readonly level: { readonly column: 'level' };
                readonly mode_of_entry: { readonly column: 'mode_of_entry' };
                readonly graduated: { readonly column: 'graduated' };
                readonly categoryId: { readonly column: 'categoryId' };
                readonly academicSession: { readonly column: 'academicSession' };
                readonly userId: { readonly column: 'userId' };
                readonly departmentId: { readonly column: 'departmentId' };
              };
            };
          };
          readonly studentCategories: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly reqDocs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'requiredDocuments';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['stuCategoryId'];
                };
                readonly through: {
                  readonly table: 'requiredDocumentsMAPstudentCategories';
                  readonly namespaceId: 'public';
                  readonly parentColumns: readonly ['stuCategoryId'];
                  readonly childColumns: readonly ['reqDocsId'];
                  readonly targetColumns: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'studentCategories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly category: { readonly column: 'category' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly mustResetPassword: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly passwordRestAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly firstName: { readonly column: 'firstName' };
                readonly lastName: { readonly column: 'lastName' };
                readonly password: { readonly column: 'password' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly isActive: { readonly column: 'isActive' };
                readonly mustResetPassword: { readonly column: 'mustResetPassword' };
                readonly passwordRestAt: { readonly column: 'passwordRestAt' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
        };
        readonly enum: {
          readonly userRole: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'STUDENT'; readonly value: 'student' },
              { readonly name: 'STAFF'; readonly value: 'staff' },
              { readonly name: 'ADMIN'; readonly value: 'admin' },
            ];
          };
          readonly dept: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'COMPUTER_SCIENCE'; readonly value: 'computer science' },
              { readonly name: 'SOFTWARE_ENGINEERING'; readonly value: 'software engineering' },
              { readonly name: 'DATA_SCIENCE'; readonly value: 'data science' },
              { readonly name: 'CYBERSECURITY'; readonly value: 'cybersecurity' },
            ];
          };
          readonly modeOfEntry: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'UTME'; readonly value: 'utme' },
              { readonly name: 'TRANSFER'; readonly value: 'transfer' },
              { readonly name: 'DIRECT_ENTRY'; readonly value: 'direct entry' },
            ];
          };
          readonly uploadStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'pending' },
              { readonly name: 'APPROVED'; readonly value: 'approved' },
              { readonly name: 'REJECTED'; readonly value: 'rejected' },
            ];
          };
          readonly registrationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NOT_STARTED'; readonly value: 'not started' },
              { readonly name: 'ONGOING'; readonly value: 'ongoing' },
              { readonly name: 'COMPLETED'; readonly value: 'completed' },
              { readonly name: 'FAILED'; readonly value: 'failed' },
            ];
          };
          readonly stuCategory: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'FRESHER'; readonly value: 'fresher' },
              { readonly name: 'RETURNING'; readonly value: 'returning' },
              { readonly name: 'FINALIST'; readonly value: 'finalist' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
